### ISSUE TITLE
Adding a message when the build is failing

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/grm#17]
Seems that currently there is no way to build if there is an error in the code and this is fine.

However it is not obvious why the build fails (no feed back to the user). Is it possible to add a feedback in this later case ?

**Comment by stropitek** [comment]
I think when the build fails there is an element of the interface that can be hovered (holding still for 1 second or so) to see the error

**Comment by targos** [comment]
Yes, you have to put your cursor over the error text.

**Comment by targos** [comment]
But if there is a syntax error in the code, the test cases should catch it. I mean you can run `npm test` locally and see what is wrong.
