### ISSUE TITLE
Problem with version on lactame.com

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/grm#18]
When we release a package the process seems to work but we never get a feedback

Warning: validateDOMNesting(...): <div> cannot appear as a child of <table>. See view > table > repo-list > div.
warning @ bundle.js:1381
bundle.js:1381 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>. See repo-list > div > tr.
warning @ bundle.js:1381

**Comment by targos** [comment]
The error that you see is always here. You should get this feedback (just tested): buttons are clickable again and version number appears (or is increased if it was visible before)
